version: '3.2'
services:
    redis:
        image: 'redis:5.0.5'
        ports:
            - "6379:6379"
        env_file:
          - .env
    db:
        image: postgres
        env_file:
          - .env
        restart: always
        volumes:
          - postgres-data:/var/lib/postgresql/data
        ports:
          - "5432:5432"
    init:
        build:
            context: .
        restart: "no"
        depends_on:
          - redis
          - db
        command: init
        env_file:
          - .env
    webserver:
        build:
            context: .
        restart: always
        depends_on:
            - init
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
        env_file:
          - .env
        volumes:
          - dag-repo:/usr/local/airflow/dag-repo

    flower:
        build:
            context: .
        restart: always
        depends_on:
            - init
        ports:
            - "5555:5555"
        command: flower
        env_file:
          - .env
    scheduler:
        build:
            context: .
        restart: always
        depends_on:
            - webserver
        command: scheduler
        env_file:
          - .env
        volumes:
            - dag-repo:/usr/local/airflow/dag-repo
    worker:
        build:
            context: .
        restart: always
        depends_on:
            - scheduler
        command: worker
        env_file:
          - .env
        volumes:
            - dag-repo:/usr/local/airflow/dag-repo
volumes:
  postgres-data:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: './postgres-data'
  dag-repo:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: '../../grok-airflow-dags'